### ISSUE TITLE
Vidjeti zasto FormAddTask ne ucitava clanove na edit

### ISSUE THREAD

**Issue by kormang** [mgrumic/ProjectGuru#11]
Nece da ucita clanove kad se edituje zadatak.

**Comment by AlexETF** [comment]
Mislim da sam to popravio. TO je zbog toga sto prilikom dodavanja clanova na projekat nisu im setovane privilegije na MEMBER. Ja sam prvo napravio da metoda addMember dodaje clana na projekat sa privilegijama NO_PRIVILEGES. Mislio sam da bi ova metoda samo trebala da doda clana na projekat, a da mu se naknadno setuju prvilegije sa setPrivileges. Prepravio sam sad to, sad metoda addMember stavlja MEMBER privilegije. Takodje nije niko pazio kod kreiranja projekta i edita, da se ne zgaze privilegije korisnika koji vec imaju veze sa projektom, da im se ne setuju svima MEMBER privilegije. I to sam  popravio.
