### ISSUE TITLE
Popraviti formu za rad sa korisnickim nalozima

### ISSUE THREAD

**Issue by kormang** [mgrumic/ProjectGuru#18]
Ne azurira se kombo boks sa privilegijama kad se klikne na drugog korisnika. Treba istestirati da li to sve radi.

**Comment by mandjic** [comment]
Rjeseno, bile su samo zakometraisane za neke korisnike. 
Da li je ovo dobro?
"Обичан корисник", Privileges.NO_PRIVILEGES.ordinal()

**Comment by mandjic** [comment]
"Екстерни корисник", Privileges.EXTERN.ordinal()
"Надзор", Privileges.INSIGHT.ordinal()
"Члан", Privileges.MEMBER.ordinal()
"Шеф пројекта", Privileges.CHEF.ordinal()
"Администратор", Privileges.ADMIN.ordinal()

**Comment by AlexETF** [comment]
Ne treba, uklonite odmah te komentare. ZAR NIKO NE CITA FACEBOOK. U aplikaciji imate samo obicne korisnike, sefa projekta i admina, za eksterne i insight to nema smisla na nivou aplikacije. To sto vam se ne azurira je vjerovatno sto imate korisnike koje imaju privilegije na nivou aplikacije setovane na Ekstern, Insight ili Clan, zato ste napravili gresku i nemojte da prepravljate nesto sto vec radi. Prvo pogledajte podatke u bazi.
