### ISSUE TITLE
Forma za dodavanje troskova i prihoda ne radi kako treba. Mora se popraviti.

### ISSUE THREAD

**Issue by kormang** [mgrumic/ProjectGuru#4]
- Cim se otvori forma ona sa desne strane prikaze ono sto je selektovano u listi sa lijeve, sto nije lose, ali omoguceno je kliknuti korisniku na dodaj.
    Mene je licno to zbunilo, ocekivao sam da ce se otvoriti nesto novo gdje cu upisati podatke, ali zapravo se samo jos jednom dodao isti iznos koji je odabran u listi, ali u KM. Treba napraviti ili da se otvori nova forma da se popune podaci ili da ima dugme "novi prihod" koje ce prebaciti formu u stanje za dodavanje novog prihoda. Pogledati kako radi forma FormActivities.

**Comment by AlexETF** [comment]
Odradicu
