### ISSUE TITLE
Gdje god su potrebni datumi trebaju biti u nasem formatu ( dd.MM.yyyy. )

### ISSUE THREAD

**Issue by kormang** [mgrumic/ProjectGuru#6]
Gdje god su potrebni datumi trebaju biti u nasem formatu ( dd.MM.yyyy. )
Za to se moze koristiti klasa koju sam napravio SerbianLocalDateStringConverter.
Njena instanca se postavi preko metode setConverter u DatePicker i on onda radi automatski, ali se moze iskorititi i na drugim mjestima, jer ima metode toString(LocalDate) i fromString(String).

**Comment by AlexETF** [comment]
Odradio
